a = open("demo.txt", "r")
a1 = a.read()
print(a1)
print(type(a))
print(type(a1))
a.close()
a = open("demo.txt", "r")
a1 = a.read()
print(a1)
print(type(a))
print(type(a1))
a.close()
a = open("demo.txt", "r")
a1 = a.read()
print(a1)
print(type(a))
print(type(a1))
a.close()
a = open("demo.txt", "r")
a1 = a.read()
print(a1)
print(type(a))
print(type(a1))
a.close()
a = open("demo.txt", "r")
a1 = a.read()
print(a1)
print(type(a))
print(type(a1))
a.close()
